# Generated by Django 5.0.6 on 2024-09-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ratting',
            new_name='rattings',
        ),
        migrations.AlterField(
            model_name='brand',
            name='imageUrl',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='imageUrl',
            field=models.URLField(),
        ),
    ]
