# Generated by Django 5.0.6 on 2024-09-06 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_ratting_product_rattings_alter_brand_imageurl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imageUrl',
            new_name='imageUrls',
        ),
    ]
