# Generated by Django 5.0.6 on 2024-09-06 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_imageurl_product_imageurls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rattings',
            new_name='ratings',
        ),
    ]
